### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by ubx** [Meisterschueler/ogn-viewer-android#12] opened 2018-05-15 15:49 UTC
Hi

I tried to build the app:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.ogn:ogn-commons-java:2.0.0-SNAPSHOT.
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.ogn:ogn-client-java:1.0.0-SNAPSHOT.
...
...

It seems that "http://maven.rushorm.com" is not reachable.

**Comment by prikril** [comment] 2018-05-15 16:40
Hi @ubx ,
yes, maven.rushorm.com is obsolete since long time, because rushorm is in central maven repository.
(https://github.com/Stuart-campbell/RushOrm/issues/125)
You can safely remove the line "maven { url "http://maven.rushorm.com" }" from your build.gradle file.
We will remove this line soon to avoid misunderstandings.

The log messages point out that you have other problems:
> Could not resolve org.ogn:ogn-commons
> Could not resolve org.ogn:ogn-client-java

Please read "Dependencies" paragraph in readme file of this project!

> The app uses two repositories from glidernet:
> https://github.com/glidernet/ogn-commons-java
> and
> https://github.com/glidernet/ogn-client-java
> Clone the Java7 files from "Android" branch!
> Use "maven install" to build them.

Please let us know if your problem is solved!
We will then close this issue.

**Comment by Meisterschueler** [comment] 2018-09-11 15:16
Not reproducable

**Closed by Meisterschueler** 2018-09-11 15:16 UTC

**Comment by Gosa7777** [comment] 2020-12-16 17:25
Hi Meisterschueler, I have a similar problem trying to build the 2 jar files. Running Maven install on them yields the following error: 
I'm new to Maven builds, so I might miss something. Any help would be appreciated.

Thanks

_[ERROR] Failed to execute goal on project ogn-client-java: Could not resolve dependencies for project org.ogn:ogn-client-java:jar:1.1.0-SNAPSHOT: Failed to collect dependencies at org.ogn:ogn-commons-java:jar:[,2.0.0): No versions available for org.ogn:ogn-commons-java:jar:[,2.0.0) within specified range -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ogn-client-java: Could not resolve dependencies for project org.ogn:ogn-client-java:jar:1.1.0-SNAPSHOT: Failed to collect dependencies at org.ogn:ogn-commons-java:jar:[,2.0.0)_
